name: Build and Push to GHCR

on:
  push:
    branches: [master]
    paths:
      - "api_service/**"
      - "ecs_worker/**"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        id: vars
        run: echo "owner=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Build & push API
        env:
          IMAGE: ghcr.io/${{ steps.vars.outputs.owner }}/api-service:latest
        run: |
          docker build -t $IMAGE ./api_service
          docker push $IMAGE

      - name: Build and Push Worker
        env:
          IMAGE: ghcr.io/${{ steps.vars.outputs.owner }}/ecs-worker:latest
        run: |
          docker build -t $GHCR_WORKER_IMAGE ./ecs_worker
          docker push $GHCR_WORKER_IMAGE
